### ISSUE TITLE
ESWC tutorial slides are missing

### ISSUE THREAD

**Issue by saidfathalla** [tetherless-world/scikg-eswc-2023#1]
hi, are you going to publish the rest of the slides?
best,
Said

**Comment by hansidm** [comment]
Hi @saidfathalla ! 
Thank you for your interest in the contents of the tutorial.
We finishing up the slides for public distribution and they should be available fairly soon here (and linked in the tutorial webpage). I'll update this issue as they become available.

**Comment by hansidm** [comment]
The slides have been published on the website. Thank you!
https://tetherless-world.github.io/scikg-eswc-2023/
